name: work_example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  rxdart: ^0.27.3
  image_picker: ^0.8.5+3
  dotted_border: ^2.0.0+2
  json_annotation: ^4.4.0
  network_image_mock: ^2.0.1
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  # flutter_pin_code_fields: ^1.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_staggered_grid_view: ^0.6.1
  extended_masked_text: ^2.3.1
  flutter_bloc: ^8.0.1
  carousel_slider: ^4.1.1
  freezed_annotation: ^2.0.3
  bloc: ^8.0.3
  equatable: ^2.0.3
  get_it: ^7.2.0
  provider: ^6.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  pretty_dio_logger: ^1.2.0-beta-1
  bloc_concurrency: ^0.2.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  relative_scale: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/cities.json

  fonts:
    - family: GloryBold
      fonts:
        - asset: fonts/glory-b.ttf
    - family: GloryMedium
      fonts:
        - asset: fonts/GloryTSI-Medium.ttf
    - family: GloryRegular
      fonts:
        - asset: fonts/GloryTSI-Regular.ttf
    - family: GloryItalic
      fonts:
        - asset: fonts/Glory-Italic.ttf
